### ISSUE TITLE
performFFT may fail if numberOfFrames is not power of two

### ISSUE THREAD

**Issue by sirius0xff** [welbesw/CoreAudioMixer#1]
Waste me half a day to find out the bug.

vDSP_fft_zrip will write to a power-of-2 number of elements, but the declared output buffer(outReal&outImag) is smaller then 2^(round(log2(numberOfFrames)). 
It makes vDSP_fft_zrip write outside of array bound, causing memory error.

**Comment by Madrox24** [comment]
Did you find a solution to fix this bug?

**Comment by sirius0xff** [comment]
I forget exactly what I did, but making `outReal` and `outImaginary` long enough should do.
I also inited them to 0 to avoid potential trouble.
```

    float outReal[length];
    float outImaginary[length];
    for(int i =0 ;i <length;++i)
        outReal[i]=outImaginary[i]=0;
```

**Comment by welbesw** [comment]
Thanks for finding this.  I've updated the latest to not crash and updated for Xcode 10.2 and Swift 5.
